version: '3.8'

services:
  api:
    image: ${DOCKER_HUB_USERNAME}/logo-detection-api:${TAG:-latest}
    container_name: logo-detection-api
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - MODEL_PATH=models/yolov8n.pt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx with simplified config
  nginx:
    image: nginx:alpine
    container_name: logo-detection-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - with-nginx